PREFIX fjmlf: <http://fjmlf.org/teacher/#>
PREFIX mfmf: <http://ex.org/mfmf/#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
  ?URI a fjmlf:enseignant;
       mfmf:annee ?rentree;
       fjmlf:anneeUniversitaire ?annee_univ;
       fjmlf:typeEtablissement ?type_etablissement;
       mfmf:region ?region;
       mfmf:academie ?academie;
       mfmf:groupe_de_corps ?categorie_personnels;
       foaf:gender ?sexe;
       mfmf:secteur_disciplinaire ?grande_discipline;
       mfmf:groupe_cnu ?groupe_cnu;
       mfmf:section_ncu ?section_cnu;
       fjmlf:nationalite ?nationalite;
       fjmlf:classeAges ?classe_ages;
       fjmlf:quotiteTravail ?quotite_travail;
       fjmlf:effectif ?effectif;
       fjmlf:IDRedion ?id_region;
       fjmlf:IDAcademie ?id_academie;
       fjmlf:codeCategoriePersonnels ?code_categorie_personnels;
       mfmf:code_section_cnu ?code_section_cnu;
       mfmf:code_groupe_cnu ?code_groupe_cnu;
       fjmlf:codeGrandeDispline ?code_grande_discipline;
} 
FROM <file:liste_enseignants.csv#delimiter=semicolon>
WHERE {
  BIND (URI(CONCAT('http://fjmlf.org/teacher/', ?code_section_cnu)) AS ?URI)
  # BIND (xsd:integer(?numEmps) AS ?numEmployees)
  # BIND (xsd:decimal(?raisedAmt) AS ?amount)
}
